export const jobs = [
  {
    "department": "Directing",
    "jobs": [
      "Director",
      "Script Supervisor",
      "Other",
      "Layout",
      "Script Coordinator",
      "Special Guest Director",
      "Assistant Director",
      "Co-Director",
      "Continuity",
      "First Assistant Director",
      "Second Assistant Director",
      "Third Assistant Director",
      "Action Director",
      "Additional Second Assistant Director",
      "Additional Third Assistant Director",
      "Assistant Director Trainee",
      "Crowd Assistant Director",
      "Field Director",
      "First Assistant Director (Prep)",
      "First Assistant Director Trainee",
      "Insert Unit Director",
      "Insert Unit First Assistant Director",
      "Second Assistant Director Trainee",
      "Second Second Assistant Director",
      "Second Unit Director",
      "Second Unit First Assistant Director",
      "Series Director",
      "Stage Director"
    ]
  },
  {
    "department": "Production",
    "jobs": [
      "Producer",
      "Executive Producer",
      "Casting",
      "Production Manager",
      "Unit Production Manager",
      "Line Producer",
      "Location Manager",
      "Other",
      "Production Supervisor",
      "Production Accountant",
      "Production Office Coordinator",
      "Finance",
      "Executive Consultant",
      "Character Technical Supervisor",
      "Development Manager",
      "Administration",
      "Executive In Charge Of Post Production",
      "Production Director",
      "Executive In Charge Of Production",
      "Publicist",
      "Associate Producer",
      "Co-Producer",
      "Co-Executive Producer",
      "Casting Associate",
      "Researcher",
      "Production Coordinator",
      "Consulting Producer",
      "Supervising Producer",
      "Senior Executive Consultant",
      "Unit Manager",
      "ADR Voice Casting",
      "Assistant Production Coordinator",
      "Assistant Production Manager",
      "Casting Assistant",
      "Casting Consultant",
      "Coordinating Producer",
      "Local Casting",
      "Script Researcher",
      "Accountant",
      "Accounting Clerk Assistant",
      "Accounting Supervisor",
      "Accounting Trainee",
      "Additional Casting",
      "Additional Production Assistant",
      "Additional Post-Production Supervisor",
      "Art Department Production Assistant",
      "Assistant Accountant",
      "Assistant Extras Casting",
      "Assistant Location Manager",
      "Assistant Unit Manager",
      "Attorney",
      "Background Casting Director",
      "Back-up Set Production Assistant",
      "Back-up Truck Production Assistant",
      "Broadcast Producer",
      "Business Affairs Coordinator",
      "Casting Coordinator",
      "Casting Director",
      "Casting Producer",
      "Casting Researcher",
      "Consulting Accountant",
      "Contract Manager",
      "Controller",
      "Data Management Technician",
      "Delegated Producer",
      "Development Producer",
      "Director of Operations",
      "Executive Assistant",
      "Executive Co-Producer",
      "Executive Producer's Assistant",
      "Extras Casting",
      "Extras Casting Assistant",
      "Extras Casting Coordinator",
      "Feature Finishing Producer",
      "Finishing Producer",
      "First Assistant Accountant",
      "First Assistant Production Coordinator",
      "General Manager",
      "Grip Production Assistant",
      "Head of Production",
      "Head of Programming",
      "Head of Research",
      "Human Resources",
      "Insert Unit Location Manager",
      "Key Accountant",
      "Key Art Production Assistant",
      "Key Grip Production Assistant",
      "Key Production Assistant",
      "Key Set Production Assistant",
      "Locale Casting Director",
      "Location Assistant",
      "Location Casting",
      "Location Coordinator",
      "Location Production Assistant",
      "Musical Casting",
      "Original Casting",
      "Payroll Accountant",
      "Post Coordinator",
      "Post Producer",
      "Post Production Accountant",
      "Post Production Coordinator",
      "Post Production Producer",
      "Post Production Technical Engineer",
      "Producer's Assistant",
      "Production Assistant",
      "Production Consultant",
      "Production Designer",
      "Production Driver",
      "Production Executive",
      "Production Runner",
      "Production Secretary",
      "Production Trainee",
      "Research Assistant",
      "Second Assistant Accountant",
      "Second Assistant Production Coordinator",
      "Second Assistant Unit Manager",
      "Second Unit Location Manager",
      "Street Casting",
      "Trainee Production Coordinator",
      "Travel Coordinator",
      "Truck Production Assistant",
      "Unit Swing"
    ]
  },
  {
    "department": "Crew",
    "jobs": [
      "Special Effects",
      "Post Production Supervisor",
      "Second Unit",
      "Choreographer",
      "Stunts",
      "Stunt Coordinator",
      "Special Effects Coordinator",
      "Supervising Technical Director",
      "Supervising Animator",
      "Production Artist",
      "Sequence Lead",
      "Second Film Editor",
      "Temp Music Editor",
      "Temp Sound Editor",
      "Sequence Supervisor",
      "Software Team Lead",
      "Software Engineer",
      "Documentation & Support",
      "Machinist",
      "Photoscience Manager",
      "Department Administrator",
      "Schedule Coordinator",
      "Supervisor of Production Resources",
      "Production Office Assistant",
      "Information Systems Manager",
      "Systems Administrators & Support",
      "Projection",
      "Post Production Assistant",
      "Sound Design Assistant",
      "Mix Technician",
      "Motion Actor",
      "Sets & Props Supervisor",
      "Compositor",
      "Tattooist",
      "Sets & Props Artist",
      "Motion Capture Artist",
      "Sequence Artist",
      "Mixing Engineer",
      "Special Sound Effects",
      "Post-Production Manager",
      "Dialect Coach",
      "Picture Car Coordinator",
      "Cableman",
      "Set Production Assistant",
      "Video Assist Operator",
      "Unit Publicist",
      "Set Medic",
      "Stand In",
      "Transportation Coordinator",
      "Transportation Captain",
      "Post Production Consulting",
      "Production Intern",
      "Utility Stunts",
      "Actor's Assistant",
      "Set Production Intern",
      "Production Controller",
      "Studio Teacher",
      "Chef",
      "Craft Service",
      "Scenic Artist",
      "Propmaker",
      "Prop Maker",
      "Transportation Co-Captain",
      "Driver",
      "Security",
      "Second Unit Cinematographer",
      "Loader",
      "Manager of Operations",
      "Quality Control Supervisor",
      "Legal Services",
      "Public Relations",
      "Score Engineer",
      "Translator",
      "Title Graphics",
      "Telecine Colorist",
      "Animatronic and Prosthetic Effects",
      "Martial Arts Choreographer",
      "Cinematography",
      "Steadycam",
      "Executive Visual Effects Producer",
      "Visual Effects Design Consultant",
      "Digital Effects Supervisor",
      "Digital Producer",
      "CG Supervisor",
      "Visual Effects Art Director",
      "Visual Effects Editor",
      "Executive in Charge of Finance",
      "Associate Choreographer",
      "Makeup Effects",
      "Editorial Staff",
      "Treatment",
      "Dramaturgy",
      "Lighting Camera",
      "Technical Supervisor",
      "CGI Supervisor",
      "Creative Consultant",
      "Script",
      "Executive Music Producer",
      "Commissioning Editor",
      "Additional Writing",
      "Additional Music",
      "Poem",
      "Thanks",
      "Creator",
      "Additional Dialogue",
      "Video Game",
      "Graphic Novel Illustrator",
      "Other",
      "Series Writer",
      "Radio Play",
      "Armorer",
      "Carpenter",
      "Aerial Coordinator",
      "Animal Coordinator",
      "Animal Wrangler",
      "Animatronics Designer",
      "Animatronics Supervisor",
      "Armory Coordinator",
      "Digital Effects Producer",
      "Drone Operator",
      "Fight Choreographer",
      "In Memory Of",
      "Marine Coordinator",
      "Pilot",
      "Presenter",
      "Pyrotechnician",
      "Techno Crane Operator",
      "Acting Double",
      "Additional Script Supervisor",
      "Administrative Assistant",
      "Assistant Chef",
      "Assistant Craft Service",
      "Assistant Picture Car Coordinator",
      "Assistant Script",
      "Assistant Vehicles Coordinator",
      "Base Camp Operator",
      "Captain Driver",
      "Cast Driver",
      "Catering",
      "Catering Head Chef",
      "Chaperone",
      "Chaperone Tutor",
      "Charge Scenic Artist",
      "Child Wrangler",
      "Clearances Coordinator",
      "Clearances Consultant",
      "Dialogue Coach",
      "Digital Supervisor",
      "Director of Communications",
      "File Footage",
      "Film Processor",
      "Floor Runner",
      "Generator Operator",
      "Head Driver",
      "Health and Safety",
      "Interactive Manager",
      "Intern",
      "Key Scenic Artist",
      "Key Special Effects",
      "Logistics Coordinator",
      "Marine Pilot",
      "Master at Arms",
      "Medical Consultant",
      "Military Consultant",
      "Playback Coordinator",
      "Police Consultant",
      "Post Production Scripts",
      "Receptionist",
      "Scientific Consultant",
      "Security Coordinator",
      "Series Publicist",
      "Set Runner",
      "Special Effects Assistant",
      "Special Effects Best Boy",
      "Special Effects Manager",
      "Special Effects Technician",
      "Specialized Driver",
      "Sponsorship Coordinator",
      "Sponsorship Director",
      "Stunt Double",
      "Stunt Driver",
      "Supervising Armorer",
      "Technical Advisor",
      "Transcriptions",
      "Unit Medic",
      "Vehicles Coordinator",
      "Vehicles Wrangler",
      "Weapons Master",
      "Weapons Wrangler"
    ]
  },
  {
    "department": "Camera",
    "jobs": [
      "Director of Photography",
      "Underwater Camera",
      "Camera Operator",
      "Still Photographer",
      "Camera Department Manager",
      "Camera Supervisor",
      "Camera Technician",
      "Other",
      "Grip",
      "Steadicam Operator",
      "Additional Camera",
      "Camera Intern",
      "Additional Photography",
      "Helicopter Camera",
      "First Assistant Camera",
      "Additional Still Photographer",
      "Aerial Camera",
      "Aerial Camera Technician",
      "Aerial Director of Photography",
      "Camera Loader",
      "Dolly Grip",
      "Epk Camera Operator",
      "Key Grip",
      "Russian Arm Operator",
      "Second Unit Director of Photography",
      "Ultimate Arm Operator",
      "Underwater Director of Photography",
      "\"A\" Camera Operator",
      "\"B\" Camera Operator",
      "\"C\" Camera Operator",
      "\"D\" Camera Operator",
      "Additional Director of Photography",
      "Additional First Assistant Camera",
      "Additional Grip",
      "Additional Key Grip",
      "Additional Second Assistant Camera",
      "Additional Set Photographer",
      "Additional Underwater Photography",
      "Assistant Camera",
      "Assistant Grip",
      "Best Boy Grip",
      "BTS Footage",
      "BTS Photographer",
      "BTS Videographer",
      "Camera Car",
      "Camera Department Production Assistant",
      "Camera Production Assistant",
      "Camera Trainee",
      "Camera Truck",
      "Clapper Loader",
      "Data Wrangler",
      "Digital Imaging Technician",
      "Drone Cinematographer",
      "Drone Pilot",
      "Epk Director",
      "Epk Producer",
      "First Assistant \"A\" Camera",
      "First Assistant \"B\" Camera",
      "First Assistant \"C\" Camera",
      "First Assistant \"D\" Camera",
      "First Company Grip",
      "Focus Puller",
      "Head of Layout",
      "Jimmy Jib Operator",
      "Libra Head Technician",
      "Phantom Operator",
      "Red Technician",
      "Second Assistant \"A\" Camera",
      "Second Assistant \"B\" Camera",
      "Second Assistant \"C\" Camera",
      "Second Assistant \"D\" Camera",
      "Second Assistant Camera",
      "Second Company Grip",
      "Set Photographer",
      "Third Assistant \"A\" Camera",
      "Third Assistant \"B\" Camera",
      "Third Assistant \"C\" Camera",
      "Third Assistant \"D\" Camera",
      "Third Assistant Camera",
      "Underwater Epk Photographer",
      "Underwater Stills Photographer",
      "Videojournalist",
      "Video Report"
    ]
  },
  {
    "department": "Visual Effects",
    "jobs": [
      "Animation",
      "Visual Effects",
      "Chief Technician / Stop-Motion Expert",
      "Creature Design",
      "Shading",
      "Modeling",
      "CG Painter",
      "Visual Development",
      "Animation Manager",
      "Animation Director",
      "Fix Animator",
      "Animation Department Coordinator",
      "Animation Fix Coordinator",
      "Animation Production Assistant",
      "Visual Effects Supervisor",
      "Mechanical & Creature Designer",
      "Battle Motion Coordinator",
      "Animation Supervisor",
      "VFX Supervisor",
      "Cloth Setup",
      ""
    ]
  }
]